import Head from "next/head";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Trirong"></link>
      </Head>

      <main>Trang này từ từ mới viết,mọi người đợi đi!</main>

      <footer></footer>
    </div>
  );
}
